CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE obligations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    site_name VARCHAR(255) NOT NULL,
    assigned_operator_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    due_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_obligation_operator FOREIGN KEY (assigned_operator_id) REFERENCES users(id)
);

CREATE TABLE executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obligation_id BIGINT NOT NULL,
    operator_id BIGINT NOT NULL,
    result VARCHAR(50) NOT NULL,
    notes VARCHAR(2000),
    executed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_execution_obligation FOREIGN KEY (obligation_id) REFERENCES obligations(id),
    CONSTRAINT fk_execution_operator FOREIGN KEY (operator_id) REFERENCES users(id)
);

CREATE TABLE evidences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    description VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_evidence_execution FOREIGN KEY (execution_id) REFERENCES executions(id)
);

CREATE INDEX idx_obligations_operator ON obligations(assigned_operator_id);
CREATE INDEX idx_executions_obligation ON executions(obligation_id);
CREATE INDEX idx_evidences_execution ON evidences(execution_id);
